mode:
  type: Cluster    #固定为Cluster 不要修改
  repository:
    type: ZooKeeper  #固定为ZooKeeper 不要修改
    props:
      namespace: ZA-192.168.7.113:13306  #替换为具体的数据库ip和端口
      server-lists: 192.168.7.113:12181   #替换为具体的zookeeper集群ip和端口
      operationTimeoutMilliseconds: 50000  #连接超时时间
dataSources:
  ds_0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource  #替换为具体的数据源完整类名
    driverClassName: com.mysql.cj.jdbc.Driver      #替换为具体的数据库驱动类名，以数据库连接池自身配置为准
    url: jdbc:mysql://192.168.7.113:13306/encrypt #替换为具体的数据库 URL 连接，以数据库连接池自身配置为准
    username: root #替换为数据库用户名，以数据库连接池自身配置为准
    password: 123456 #替换为数据库密码，以数据库连接池自身配置为准
    maxPoolSize: 10 #最大连接数
    # 其他配置 配置的名字以数据库连接池为准

# 单表全部由插件管理 不需要修改
rules:
- !SINGLE
  tables:
    - "*.*"
#是否打印SQL语句 逻辑+实际 SQL
props:
  sql-show: true
